---
  


  - name: Copy Dockerfile 
    template:
      src: roles/Master_creation/templates/Dockerfile
      dest: /tmp

  - name: Copy setup-master.sh 
    copy:
      src: roles/Master_creation/files/setup-master.sh
      dest: /tmp

  - name: Build an master image 
    docker_image:
      path: /tmp
      name: "{{ master_img_name }}"

  - name: Creating pg_master container
    docker_container:
      name: "{{ master_cont_name }}"
      image: "{{ master_img_name }}"
      env:
        POSTGRES_USER="{{ pg_user }}"
        POSTGRES_PASSWORD="{{ pg_password }}"
        POSTGRES_DB="{{ pg_database }}"
        PG_REP_USER="{{ pg_rep_user }}"
        PG_REP_PASSWORD="{{ pg_rep_password }}"
      ports:
        - 5432:5432
      volumes:
        - "{{ volume_name }}:/var/lib/postgresql/data"
      networks:
        - name: "{{ network_name }}"
      state: started








